### ISSUE TITLE
error,please help me

### ISSUE THREAD

**Issue by hotpotlover-yang** [zehuamama/tinyrpc#24]
I am a beginner of golang language，with the previous steps have been successfully executed,   there is a error occur when i execute the command :"protoc --tinyrpc_out=. arith.proto --go_out=. arith.proto", 
and the error is :
"protoc-gen-tinyrpc: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--tinyrpc_out: protoc-gen-tinyrpc: Plugin failed with status code 1."

what should i do to fix it? thanks a lot

**Comment by ajwlforever** [comment]
I also encountered this problem yesterday, the protoc-gen-tinyrp command is not in GOPATH.
I use
```
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
``` 
![image](https://github.com/zehuamama/tinyrpc/assets/39605627/2150db75-32bb-43b4-b2c4-6e632e986a44)
download protoc-gen-tinyrp in gopath and this path should be in system enviroments.

**Comment by andrew111-oo** [comment]
protoc-gen-tinyrpc  在这目录下  保证main.go 文件没有报错 可以正常运行 然后执行 go build  简单来说就是把这个目录编译成exe文件  然后放到proto目录下使用

**Comment by psyschotropiczh** [comment]
是谁专业分流倒数第一名却读到软件工程的？是谁发的病毒到班级群和网吧里面的
